# These are supported funding model platforms

github: khoirulaksara # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
thanks_dev: khoirulaksara # Replace with a single thanks.dev username
custom: ["https://www.paypal.me/gonzsky", "Khoirul Anwar"]
